### ISSUE TITLE
Value option not working

### ISSUE THREAD

**Issue by MaximeTroiano** [soundar24/roundSlider#13] opened 2015-12-28 22:41 UTC
Here is my code:
![image](https://cloud.githubusercontent.com/assets/13046607/12026650/65933080-adbc-11e5-9e8b-9aeba54038e8.png)

And here is my slider:
![image](https://cloud.githubusercontent.com/assets/13046607/12026654/7c9856ac-adbc-11e5-9677-ccb29f8ff70b.png)

**Comment by soundar24** [comment] 2015-12-29 16:55
I have tried with the code you provided, but i can't reproduce the issue. I have created a jsFiddle with the codes you provided, in that the **value** option was working fine. Please check the below demo:
http://jsfiddle.net/soundar24/LpuLe9tr/205/

Please check this demo and update me if you faced any issues.

**Comment by soundar24** [comment] 2016-01-23 11:34
Closed this issue, if you have faced any issues still then you can reopen this issue.

**Closed as completed by soundar24** 2016-01-23 11:34 UTC
